services:
  svelte_training:
    build:
      context: .
      dockerfile: Dockerfile
    image: node20:training_svelte
    container_name: node_svelte
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/svelte-training:rw
      # コンテナ側の node_modules を ホストと同期しない
      - sveltekit-node_modules-volume:/svelte-training/app/node_modules
    ports:
      - "127.0.0.1:5000:8080"
    command: bash
volumes:
  sveltekit-node_modules-volume:
    name: sveltekit-node_modules
    driver: local
