services:
  svelte_training:
    build:
      context: .
      dockerfile: Dockerfile
    image: node20:training_svelte
    container_name: node_svelte
    tty: true
    environment:
      - NODE_ENV=development
      - SERVER_PORT=5000
    volumes:
      - .:/user/src/svelte-training:rw
    ports:
      - "127.0.0.1:5000:5000"
    command: bash
